const {
    GOVERNANCE_TOKEN_ADDRESS,
    QUORUM_PERCENTAGE,
    TIMELOCK_ADDRESS,
    VOTING_DELAY,
    VOTING_PERIOD
} = require("../helper-hardhat-config");

module.exports = [
    GOVERNANCE_TOKEN_ADDRESS,
    TIMELOCK_ADDRESS,
    QUORUM_PERCENTAGE,
    VOTING_PERIOD,
    VOTING_DELAY
];